FROM python:3.10-slim

WORKDIR /app

COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

COPY api_app ./

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]