apiVersion: v1
kind: Service
metadata:
  name: mochi-api
spec:
  selector:
    app: mochi-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mochi-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mochi-api
  template:
    metadata:
      labels:
        app: mochi-api
    spec:
      containers:
        - name: api
          image: localhost:5000/mochi-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis"