apiVersion: apps/v1
kind: Deployment
metadata:
  name: mochi-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mochi-worker
  template:
    metadata:
      labels:
        app: mochi-worker
    spec:
      containers:
        - name: worker
          image: localhost:5000/mochi-worker:v3
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: MOCHI_WEIGHTS_DIR
              value: "/weights"
          volumeMounts:
            - name: weights
              mountPath: /weights
              readOnly: true
          resources:
            limits:
              nvidia.com/gpu: 2
      volumes:
        - name: weights
          hostPath:
            path: /home/ubuntu/mochi_weights
            type: Directory
